/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Button, StyleSheet, Text, View} from 'react-native';
import OneFlow from '@1flow-inc/react-native-1flow-sdk';

export default class App extends Component<{}> {
  constructor(props) {
    super(props);
    this.myRef = React.createRef();
    let projectKey = '';
    OneFlow.configure(projectKey);
    this.logUserTest();
  }
  componentDidMount() {
    //
    OneFlow.eventEmitter1Flow.addListener(
      'oneFlowSurveyFinishNotification',
      this.oneFlowSurveyFinishNotification,
    );
  }

  oneFlowSurveyFinishNotification = eventObj => {
    console.log(eventObj);
  };

  logUserTest = async () => {
    await OneFlow.logUser('test_rn_2023.4.19', {tested_by: 'Test User'});
  };

  recordEventNameTest = async () => {
    await OneFlow.recordEventName('first_open', null);
    console.log('recordEventNameTest');
  };

  render() {
    return (
      <View
        style={styles.container}
        ref={ref => {
          this.myView = ref;
        }}>
        <Text style={styles.welcome}>Start Survey☆</Text>
        <Button
          onPress={() => this.logUserTest()}
          title="Log User"
          color="#841584"
        />
        <Button
          onPress={() => this.recordEventNameTest()}
          title="Record Event Name"
          color="#841584"
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
